name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy on PythonAnywhere
        env:
          PA_USERNAME: ${{ secrets.PA_USERNAME }}
          PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        run: |
          curl -X POST "https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/consoles/" \
            -H "Authorization: Token $PA_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "executable": "bash",
              "arguments": [
                "-c",
                "cd ~/bookstore && \
                 git pull origin main && \
                 source .venv/bin/activate && \
                 pip install -r requirements.txt && \
                 python manage.py migrate && \
                 python manage.py collectstatic --noinput && \
                 pa_reload_webapp benhurk.pythonanywhere.com"
              ]
            }'
