name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Call PythonAnywhere API to pull latest code
        run: |
          curl -X POST https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/consoles/ \
            -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"executable": "bash", "arguments": ["-c", "cd ~/bookstore && \
                  git pull origin main && \
                  poetry install --no-root \
                  source .venv/bin/activate && \
                  python manage.py migrate && \
                  python manage.py collectstatic --noinput && \
                  pa_reload_webapp benhurk.pythonanywhere.com"]}'
